import './globals.css'
import { fredoka } from './Font'
import { NavBar } from './components/NavBar'

export const metadata = {
  title: 'Car Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fredoka.className}>
        <NavBar />
        {children}
        </body>
    </html>
  )
}
